In [31]:
import torch
import torch.nn as nn
from torch.nn import functional as F
import numpy as np
import time
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)   

cpu


In [32]:
%%time
start_time = time.time()
# matrix operations here
zeroes = torch.zeros(1,1)
end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f} seconds")

0.00004125 seconds
CPU times: user 550 µs, sys: 380 µs, total: 930 µs
Wall time: 674 µs


In [33]:
torch_rand1 = torch.rand(100, 100, 100, 100).to(device)
torch_rand2 = torch.rand(100, 100, 100, 100).to(device)
np_rand1 = torch.rand(100, 100, 100, 100)
np_rand2 = torch.rand(100, 100, 100, 100)

start_time = time.time()
rand = (torch_rand1 * torch_rand2)

end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

start_time = time.time()

rand = np.multiply(np_rand1, np_rand2)
end_time = time.time()
elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

0.17600203
0.37199426


In [34]:
#Define a probability tensor

probabilities = torch.tensor([0.1, 0.9])
samples = torch.multinomial(probabilities, 10, replacement=True)
print(samples)  

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])


In [35]:
tensor = torch.tensor(1, 2, 3, 4)

out = torch.cat((tensor, torch.tensor[5]), dim=0)
out

TypeError: tensor() takes 1 positional argument but 4 were given

In [ ]:
out = torch.tril(torch.ones(5, 5))  
out    

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [ ]:
out = torch.triu(torch.ones(5, 5))
out   

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [ ]:
out = torch.zeros(5,5).masked_fill(torch.tril(torch.ones(5,5)) == 0, float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [ ]:
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [ ]:
input = torch.zeros(2,3,4)
out = input.transpose(0, 2)
out.shape   

torch.Size([4, 3, 2])

In [ ]:
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4,5,6])
tensor3 = torch.tensor([7,8,9])

#stack the tensors along the new dimension

stacked_tensor = torch.stack((tensor1, tensor2, tensor3))
stacked_tensor


tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:

sample = torch.tensor([10., 10., 10.])
linear = nn.Linear(3, 3, bias = False)
print(linear(sample))


tensor([  5.2993, -10.6200,  -8.1112], grad_fn=<SqueezeBackward4>)


In [ ]:
import torch.nn.functional as F

#Create a tensor

tensor1 = torch.tensor([1.0, 2.0, 3.0])

#Apply softmax using torch.nn.functional.softmax()
soft_output = F.softmax(tensor1, dim=0)

print(soft_output)


tensor([0.0900, 0.2447, 0.6652])


In [ ]:
vocab_size = 1000
embedding_dim = 100
embedding = nn.Embedding(vocab_size, embedding_dim)

#Create some input indicees
input_indices = torch.LongTensor([1, 5, 3,2 ])

#Apply the embedding layer
embedded_output = embedding(input_indices)

#The output will be a tensor of shape (4, 100), where 4 is the number of input indices
# and 100 is the embedding dimension of the embedding layer
print(embedded_output.shape)

torch.Size([4, 100])


In [36]:
a = torch.tensor([[1,2],[3,4],[5,6]])
b = torch.tensor([[7,8,9],[10,11,12]])
print(a @ b)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


In [40]:
int_64 = torch.randint(1, (3,2)).float()

#type int_64
float_32 = torch.rand(2,3)

print(int_64.dtype)
print(float_32.dtype)
result = torch.matmul(int_64, float_32)
print(result)

torch.float32
torch.float32
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [44]:
a = torch.rand(2, 3, 5)
print(a.shape)
x, y, z = a.shape
a = a.view(x, y , z)
print(x, y, z)
print(a.shape)

torch.Size([2, 3, 5])
2 3 5
torch.Size([2, 3, 5])


In [48]:
## Relu function
x = torch.tensor([100], dtype=torch.float32)
y = F.tanh(x)
print(y)

tensor([1.])


In [ ]:
## transformer model architecture is used for NLP tasks. There are all these parameters that are passed to the model. 
## The model is then trained on the data and the loss is calculated. The loss is then backpropagated through the model to update the weights.
## With Transfomer models we have inputs that are given embeddings as input embeddings and output embeddings. There are learnable parameters that are updated during training.
## After we've given these inputs embeddings and positional encondings, we pass them through the encoder and decoder layers. The encoder and decoder layers are made up of multi-head attention layers and feedforward layers.