In [18]:
import torch
import numpy as np
import time
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)   

cpu


In [19]:
%%time
start_time = time.time()
# matrix operations here
zeroes = torch.zeros(1,1)
end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f} seconds")

0.00058794 seconds
CPU times: user 725 µs, sys: 838 µs, total: 1.56 ms
Wall time: 922 µs


In [20]:
torch_rand1 = torch.rand(100, 100, 100, 100).to(device)
torch_rand2 = torch.rand(100, 100, 100, 100).to(device)
np_rand1 = torch.rand(100, 100, 100, 100)
np_rand2 = torch.rand(100, 100, 100, 100)

start_time = time.time()
rand = (torch_rand1 * torch_rand2)

end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

start_time = time.time()

rand = np.multiply(np_rand1, np_rand2)
end_time = time.time()
elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

0.13235497
0.29528403


In [21]:
#Define a probability tensor

probabilities = torch.tensor([0.1, 0.9])
samples = torch.multinomial(probabilities, 10, replacement=True)
print(samples)  

tensor([1, 1, 0, 1, 1, 1, 1, 1, 1, 1])


In [22]:
tensor = torch.tensor(1, 2, 3, 4)

out = torch.cat((tensor, torch.tensor[5]), dim=0)
out

TypeError: tensor() takes 1 positional argument but 4 were given

In [ ]:
out = torch.tril(torch.ones(5, 5))  
out    

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [ ]:
out = torch.triu(torch.ones(5, 5))
out   

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [ ]:
out = torch.zeros(5,5).masked_fill(torch.tril(torch.ones(5,5)) == 0, float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [ ]:
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [ ]:
input = torch.zeros(2,3,4)
out = input.transpose(0, 2)
out.shape   

torch.Size([4, 3, 2])

In [ ]:
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4,5,6])
tensor3 = torch.tensor([7,8,9])

#stack the tensors along the new dimension

stacked_tensor = torch.stack((tensor1, tensor2, tensor3))
stacked_tensor


tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
import torch.nn as nn

sample = torch.tensor([10., 10., 10.])
linear = nn.Linear(3, 3, bias = False)
print(linear(sample))


tensor([  5.2993, -10.6200,  -8.1112], grad_fn=<SqueezeBackward4>)


In [23]:
import torch.nn.functional as F

#Create a tensor

tensor1 = torch.tensor([1.0, 2.0, 3.0])

#Apply softmax using torch.nn.functional.softmax()
soft_output = F.softmax(tensor1, dim=0)

print(soft_output)


tensor([0.0900, 0.2447, 0.6652])
